### ISSUE TITLE
Can you give an explanation how to use wordlists ?

### ISSUE THREAD

**Issue by Warlord711** [RapidDNS/Afuzz#2]
Can you give an explanation how to use wordlists ?

There is a point about wordlists and variables that can be used (i dont really see why and how).
Can you maybe give an example how it is intended to work ?

**Comment by insightglacier** [comment]
Regarding wordlists, you can use the -w option to select your own dictionary.

Variables supported by wordlist include
Take admin.google.com as an example
%ext%: file suffix, parameter -e or default content
%subdomain%: The complete subdomain name, ie admin.google.com
%sub%: the front part of the subdomain name, ie admin
%domain%: google
%rootdomain%: google.com

**Comment by insightglacier** [comment]
> Can you give an explanation how to use wordlists ?
> 
> There is a point about wordlists and variables that can be used (i dont really see why and how). Can you maybe give an example how it is intended to work ?

Regarding wordlists, you can use the -w option to select your own dictionary.

Variables supported by wordlist include
Take admin.google.com as an example
%ext%: file suffix, parameter -e or default content
%subdomain%: The complete subdomain name, ie admin.google.com
%sub%: the front part of the subdomain name, ie admin
%domain%: google
%rootdomain%: google.com
