### ISSUE TITLE
优化结果显示

### ISSUE THREAD

**Issue by safebaseline** [RapidDNS/Afuzz#3]
建议参照dirseach 可以增加full path ，即url+path显示：http://x.x.x.x/admin.php

**Comment by RapidDNS** [comment]
> 建议参照dirseach 可以增加full path ，即url+path显示：http://x.x.x.x/admin.php

Get

**Comment by safebaseline** [comment]
已收到

**Comment by RapidDNS** [comment]
> 已收到

use -f or --fullpath
